# Generated by Django 4.0.3 on 2022-04-13 05:48

from django.db import migrations

def create_initial_novel_genres(apps, schema_editor):
    genres = ['Aventure', 'Romance', 'Action', 'Horreur', 'Fantasy', 'Enfants', 'Autres', 'Inconnu']
    NovelGenre = apps.get_model('main', 'NovelGenre')

    for genre in genres:
        new_genre = NovelGenre.objects.create(title=genre)
        new_genre.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_novel_reads'),
    ]

    operations = [
        migrations.RunPython(create_initial_novel_genres),
    ]
